# Generated by Django 5.2.7 on 2025-10-18 08:24
# Generated by Django 5.2.7 on 2025-10-18 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_section'),
        ('main', '0002_user'),
    ]

    operations = [
    ]
