# Generated by Django 5.2.7 on 2025-10-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_merge_0002_section_0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='default_mail_sender',
            field=models.EmailField(blank=True, default='', help_text='Default sender email for Graph API mail operations', max_length=254, verbose_name='Default Mail Sender'),
        ),
        migrations.AddField(
            model_name='settings',
            name='graph_api_base_url',
            field=models.CharField(blank=True, default='https://graph.microsoft.com/v1.0', help_text='Microsoft Graph API base URL', max_length=255, verbose_name='Graph API Base URL'),
        ),
        migrations.AddField(
            model_name='settings',
            name='graph_api_enabled',
            field=models.BooleanField(default=False, help_text='Enable Microsoft Graph API integration', verbose_name='Enable Graph API'),
        ),
        migrations.AddField(
            model_name='settings',
            name='graph_api_scopes',
            field=models.TextField(blank=True, default='https://graph.microsoft.com/.default', help_text='Comma-separated list of Graph API scopes', verbose_name='Graph API Scopes'),
        ),
        migrations.AddField(
            model_name='settings',
            name='sharepoint_site_id',
            field=models.CharField(blank=True, default='', help_text='SharePoint site ID for document operations', max_length=255, verbose_name='SharePoint Site ID'),
        ),
    ]
