# Generated by Django 5.2.7 on 2025-10-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_settings_default_mail_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='github_api_base_url',
            field=models.CharField(blank=True, default='https://api.github.com', help_text='GitHub API base URL', max_length=255, verbose_name='GitHub API Base URL'),
        ),
        migrations.AddField(
            model_name='settings',
            name='github_api_enabled',
            field=models.BooleanField(default=False, help_text='Enable GitHub API integration', verbose_name='Enable GitHub API'),
        ),
        migrations.AddField(
            model_name='settings',
            name='github_default_owner',
            field=models.CharField(blank=True, default='', help_text='Default owner for GitHub operations', max_length=255, verbose_name='Default GitHub Owner'),
        ),
        migrations.AddField(
            model_name='settings',
            name='github_default_repo',
            field=models.CharField(blank=True, default='', help_text='Default repository for GitHub operations', max_length=255, verbose_name='Default GitHub Repository'),
        ),
    ]
