# Generated by Django 5.2.7 on 2025-10-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_settings_github_api_base_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='kigate_token',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='kigate_url',
        ),
        migrations.AddField(
            model_name='settings',
            name='kigate_api_base_url',
            field=models.CharField(blank=True, default='http://localhost:8000', help_text='KiGate API base URL', max_length=255, verbose_name='KiGate API Base URL'),
        ),
        migrations.AddField(
            model_name='settings',
            name='kigate_api_enabled',
            field=models.BooleanField(default=False, help_text='Enable KiGate API integration', verbose_name='Enable KiGate API'),
        ),
        migrations.AddField(
            model_name='settings',
            name='kigate_api_timeout',
            field=models.IntegerField(default=30, help_text='Timeout for KiGate API requests in seconds', verbose_name='KiGate API Timeout'),
        ),
        migrations.AddField(
            model_name='settings',
            name='kigate_api_token',
            field=models.CharField(blank=True, default='', help_text='KiGate API authentication token (client_id:client_secret)', max_length=255, verbose_name='KiGate API Token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('developer', 'Developer'), ('user', 'User'), ('viewer', 'Viewer')], default='user', max_length=20),
        ),
    ]
