# Generated by Django 5.2.7 on 2025-10-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_update_kigate_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='openai_api_base_url',
            field=models.CharField(blank=True, default='https://api.openai.com/v1', help_text='OpenAI API base URL', max_length=255, verbose_name='OpenAI API Base URL'),
        ),
        migrations.AddField(
            model_name='settings',
            name='openai_api_enabled',
            field=models.BooleanField(default=False, help_text='Enable OpenAI API integration', verbose_name='Enable OpenAI API'),
        ),
        migrations.AddField(
            model_name='settings',
            name='openai_api_timeout',
            field=models.IntegerField(default=30, help_text='Timeout for OpenAI API requests in seconds', verbose_name='OpenAI API Timeout'),
        ),
        migrations.AddField(
            model_name='settings',
            name='openai_default_model',
            field=models.CharField(blank=True, default='gpt-4', help_text='Default model for OpenAI API (e.g., gpt-4, gpt-3.5-turbo)', max_length=100, verbose_name='Default OpenAI Model'),
        ),
    ]
