# Generated by Django 5.2.7 on 2025-10-18 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_passwordresettoken'),
        ('main', '0007_settings_openai_api_base_url_and_more'),
    ]

    operations = [
    ]
