# Generated by Django 5.2.7 on 2025-10-18 15:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_item_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('new', 'Neu'), ('spec_review', 'Spezifikation Review'), ('working', 'Working'), ('ready', 'Ready'), ('done', 'Erledigt'), ('rejected', 'Verworfen')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='ItemSimilarity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='main.item')),
                ('target_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_from', to='main.item')),
            ],
            options={
                'verbose_name': 'Item Similarity',
                'verbose_name_plural': 'Item Similarities',
                'ordering': ['-similarity_score'],
                'unique_together': {('source_item', 'target_item')},
            },
        ),
    ]
