# Generated by Django 5.2.7 on 2025-10-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_item_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('new', 'Neu'), ('spec_review', 'Spezifikation Review'), ('working', 'Working'), ('ready', 'Ready'), ('done', 'Erledigt'), ('rejected', 'Verworfen')], default='new', max_length=20),
        ),
    ]
