# Generated by Django 5.2.7 on 2025-10-18 20:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_item_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('dependency', 'Abhängigkeit'), ('similar', 'Ähnlich'), ('synergy', 'Synergieeffekt'), ('parent', 'Parent'), ('child', 'Child'), ('other', 'Sonstige')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='main.item')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='main.item')),
            ],
            options={
                'verbose_name': 'Relation',
                'verbose_name_plural': 'Relations',
                'ordering': ['-created_at'],
                'unique_together': {('source', 'target', 'type')},
            },
        ),
    ]
