# Generated by Django 5.2.7 on 2025-10-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_add_log_analysis_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
    ]
