# Generated by Django 5.2.7 on 2025-10-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_tag_usage_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
