# Generated by Django 5.2.7 on 2025-10-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_add_tag_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='weaviate_api_key',
            field=models.CharField(blank=True, default='', help_text='Weaviate Cloud API Key', max_length=255, verbose_name='WEAVIATE_API_KEY'),
        ),
        migrations.AddField(
            model_name='settings',
            name='weaviate_cloud_enabled',
            field=models.BooleanField(default=False, help_text='Enable Weaviate Cloud (if disabled, local configuration is used)', verbose_name='Cloud'),
        ),
        migrations.AddField(
            model_name='settings',
            name='weaviate_url',
            field=models.CharField(blank=True, default='', help_text='Weaviate Cloud URL', max_length=255, verbose_name='WEAVIATE_URL'),
        ),
    ]
