# Generated by Django 5.2.7 on 2025-10-21 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_client_item_clients_user_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_tasks', to='main.user'),
        ),
    ]
