# Generated by Django 5.2.7 on 2025-10-21 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_add_requester_to_task'),
        ('main', '0017_milestone_task_milestone'),
    ]

    operations = [
    ]
