# Generated by Django 5.2.7 on 2025-10-21 21:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_merge_20251021_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('sharepoint_file_id', models.CharField(blank=True, default='', max_length=255)),
                ('sharepoint_url', models.URLField(blank=True, default='', max_length=1000)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('weaviate_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.item')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to='main.user')),
            ],
            options={
                'verbose_name': 'Item File',
                'verbose_name_plural': 'Item Files',
                'ordering': ['-created_at'],
            },
        ),
    ]
