# Generated by Django 5.2.7 on 2025-10-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_itemfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='ms_sso_client_id',
            field=models.CharField(blank=True, default='', help_text='Microsoft Azure AD Application (Client) ID for SSO', max_length=255, verbose_name='MS SSO Client ID'),
        ),
        migrations.AddField(
            model_name='settings',
            name='ms_sso_client_secret',
            field=models.CharField(blank=True, default='', help_text='Microsoft Azure AD Client Secret for SSO (optional for some flows)', max_length=255, verbose_name='MS SSO Client Secret'),
        ),
        migrations.AddField(
            model_name='settings',
            name='ms_sso_enabled',
            field=models.BooleanField(default=False, help_text='Enable Microsoft Identity SSO authentication', verbose_name='Enable Microsoft SSO'),
        ),
        migrations.AddField(
            model_name='settings',
            name='ms_sso_tenant_id',
            field=models.CharField(blank=True, default='', help_text='Microsoft Azure AD Tenant ID for SSO', max_length=255, verbose_name='MS SSO Tenant ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='auth_type',
            field=models.CharField(choices=[('local', 'Local Authentication'), ('msauth', 'Microsoft Authentication')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, default='', help_text='URL to user avatar image', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='ms_user_id',
            field=models.CharField(blank=True, default='', help_text='Microsoft User ID (OID)', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
