# Generated by Django 5.2.7 on 2025-10-22 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_settings_ms_sso_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inherit_context',
            field=models.BooleanField(default=False, help_text='Steuert, ob Beschreibung, Tags, Milestones vom Parent geerbt werden'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Kennzeichnet, ob das Item als Vorlage dient'),
        ),
        migrations.AddField(
            model_name='item',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='main.item'),
        ),
    ]
