# Generated by Django 5.2.7 on 2025-10-22 11:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_add_hierarchical_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='zammad_api_token',
            field=models.CharField(blank=True, default='', help_text='API token for authentication', max_length=255, verbose_name='Zammad API Token'),
        ),
        migrations.AddField(
            model_name='settings',
            name='zammad_api_url',
            field=models.CharField(blank=True, default='', help_text='Base URL of the Zammad instance', max_length=255, verbose_name='Zammad API URL'),
        ),
        migrations.AddField(
            model_name='settings',
            name='zammad_enabled',
            field=models.BooleanField(default=False, help_text='Enable Zammad ticket synchronization', verbose_name='Enable Zammad Integration'),
        ),
        migrations.AddField(
            model_name='settings',
            name='zammad_groups',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of group names to monitor', verbose_name='Zammad Groups'),
        ),
        migrations.AddField(
            model_name='settings',
            name='zammad_sync_interval',
            field=models.IntegerField(default=15, help_text='Interval in minutes for periodic synchronization', verbose_name='Zammad Sync Interval'),
        ),
        migrations.AddField(
            model_name='task',
            name='external_id',
            field=models.CharField(blank=True, default='', help_text='External system ID (Zammad ticket ID, etc.)', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='external_url',
            field=models.URLField(blank=True, default='', help_text='URL to external system resource', max_length=500),
        ),
        migrations.AddField(
            model_name='task',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Direct section assignment for tickets', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='main.section'),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('task', 'Task'), ('feature', 'Feature'), ('bug', 'Bug'), ('ticket', 'Ticket'), ('maintenance', 'Maintenance')], default='task', help_text='Task type classification', max_length=20),
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('file_path', models.CharField(blank=True, default='', help_text='Local file path', max_length=500)),
                ('sharepoint_file_id', models.CharField(blank=True, default='', max_length=255)),
                ('sharepoint_url', models.URLField(blank=True, default='', max_length=1000)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('weaviate_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.task')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_task_files', to='main.user')),
            ],
            options={
                'verbose_name': 'Task File',
                'verbose_name_plural': 'Task Files',
                'ordering': ['-created_at'],
            },
        ),
    ]
