# Generated by Django 5.2.7 on 2025-10-22 14:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_settings_zammad_api_token_settings_zammad_api_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Manuelle oder KI-basierte Beschreibung'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('planned', 'Geplant'), ('in_progress', 'In Arbeit'), ('completed', 'Abgeschlossen')], default='planned', max_length=20),
        ),
        migrations.AddField(
            model_name='milestone',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='KI-Zusammenfassung über alle Kontextobjekte'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='weaviate_id',
            field=models.UUIDField(blank=True, help_text='Verweis auf das Embedding im Vektorspeicher', null=True),
        ),
        migrations.CreateModel(
            name='MilestoneContextObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('file', 'Datei'), ('email', 'E-Mail'), ('transcript', 'Transkript'), ('note', 'Notiz')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('source_id', models.CharField(blank=True, default='', help_text='GUID oder Pfad', max_length=255)),
                ('url', models.URLField(blank=True, default='', help_text='URL zum Dokument', max_length=1000)),
                ('content', models.TextField(blank=True, default='', help_text='Textinhalt des Objekts')),
                ('summary', models.TextField(blank=True, default='', help_text='KI-generierte Zusammenfassung')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Automatisch extrahierte Tags')),
                ('derived_tasks', models.JSONField(blank=True, default=list, help_text='Abgeleitete Aufgaben (JSON)')),
                ('analyzed', models.BooleanField(default=False, help_text='Wurde bereits von KI analysiert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_objects', to='main.milestone')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_context_objects', to='main.user')),
            ],
            options={
                'verbose_name': 'Milestone Context Object',
                'verbose_name_plural': 'Milestone Context Objects',
                'ordering': ['-created_at'],
            },
        ),
    ]
