# Generated by Django 5.2.7 on 2025-10-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_add_milestone_knowledge_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='kigate_max_tokens',
            field=models.IntegerField(default=10000, help_text='Maximum number of tokens to send per KiGate API request (content will be chunked if larger)', verbose_name='KiGate Max Tokens per Request'),
        ),
    ]
