# Generated by Django 5.2.7 on 2025-10-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_add_kigate_max_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='openai_max_tokens',
            field=models.IntegerField(default=10000, help_text='Maximum number of tokens to send per OpenAI API request (content will be chunked if larger)', verbose_name='OpenAI Max Tokens per Request'),
        ),
    ]
