# Generated by Django 5.2.7 on 2025-10-23 05:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_add_openai_max_tokens_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneSummaryVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_text', models.TextField(help_text='Snapshot of the summary text')),
                ('version_number', models.IntegerField(default=1, help_text='Sequential version number')),
                ('optimized_by_ai', models.BooleanField(default=False, help_text='Whether this version was AI-optimized')),
                ('agent_name', models.CharField(blank=True, default='', help_text='Name of the AI agent used', max_length=255)),
                ('model_name', models.CharField(blank=True, default='', help_text='AI model used for optimization', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone_summary_versions', to='main.user')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_versions', to='main.milestone')),
            ],
            options={
                'verbose_name': 'Milestone Summary Version',
                'verbose_name_plural': 'Milestone Summary Versions',
                'ordering': ['-version_number'],
                'unique_together': {('milestone', 'version_number')},
            },
        ),
    ]
