# Generated by Django 5.2.7 on 2025-10-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_add_milestone_summary_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='google_pse_enabled',
            field=models.BooleanField(default=False, help_text='Enable Google Programmable Search Engine integration', verbose_name='Enable Google PSE'),
        ),
        migrations.AddField(
            model_name='settings',
            name='google_search_api_key',
            field=models.CharField(blank=True, default='', help_text='Google Custom Search API Key', max_length=255, verbose_name='Google Search API Key'),
        ),
        migrations.AddField(
            model_name='settings',
            name='google_search_cx',
            field=models.CharField(blank=True, default='', help_text='Google Custom Search Engine ID (CX)', max_length=255, verbose_name='Google Search CX'),
        ),
    ]
