# Generated by Django 5.2.7 on 2025-10-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_add_milestone_summary_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='github_copilot_username',
            field=models.CharField(blank=True, default='', help_text='GitHub username to assign issues to (e.g., copilot)', max_length=255, verbose_name='GitHub Copilot Username'),
        ),
    ]
