# Generated by Django 5.2.7 on 2025-10-23 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_add_google_pse_settings'),
        ('main', '0027_settings_github_copilot_username'),
    ]

    operations = [
    ]
