# Generated by Django 5.2.7 on 2025-10-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_merge_20251023_1827'),
        ('main', '0028_merge_20251023_1845'),
    ]

    operations = [
    ]
