# Generated by Django 5.2.7 on 2025-10-23 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_merge_20251023_1857'),
        ('main', '0029_merge_20251023_1909'),
    ]

    operations = [
    ]
