# Generated by Django 5.2.7 on 2025-10-24 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_merge_20251023_2029'),
        ('main', '0030_merge_20251023_2114'),
    ]

    operations = [
    ]
