# Generated by Django 5.2.7 on 2025-10-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_add_user_first_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='channel_id',
            field=models.CharField(blank=True, default='', help_text='Channel ID aus dem Teams Workspace', max_length=255, verbose_name='Teams Channel ID'),
        ),
        migrations.AddField(
            model_name='settings',
            name='team_welcome_post',
            field=models.TextField(blank=True, default='Willkommen im Channel für {{Item}}! Hier können Sie Nachrichten zu diesem Item senden und diskutieren.', help_text='Vorlage für einen Begrüßungspost. Verwenden Sie {{Item}} als Platzhalter für den Item-Titel.', verbose_name='Teams Welcome Post Template'),
        ),
        migrations.AddField(
            model_name='settings',
            name='teams_enabled',
            field=models.BooleanField(default=False, help_text='Aktiviert/Deaktiviert die Teams-Integration', verbose_name='Enable Teams Integration'),
        ),
        migrations.AddField(
            model_name='settings',
            name='teams_team_id',
            field=models.CharField(blank=True, default='', help_text='ID des Teams (Workspace), das beobachtet wird', max_length=255, verbose_name='Teams Team ID'),
        ),
    ]
