# Generated by Django 5.2.7 on 2025-10-24 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_merge_20251024_0710'),
        ('main', '0032_add_user_first_last_name'),
    ]

    operations = [
    ]
