# Generated by Django 5.2.7 on 2025-10-24 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_add_teams_integration'),
        ('main', '0033_merge_20251024_0829'),
    ]

    operations = [
    ]
