# Generated by Django 5.2.7 on 2025-10-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_merge_20251024_0857'),
        ('main', '0034_merge_20251024_0907'),
    ]

    operations = [
    ]
