# Generated by Django 5.2.7 on 2025-10-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_merge_20251024_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='graph_poll_interval',
            field=models.IntegerField(default=60, help_text='Interval in seconds for polling Teams channels for new messages', verbose_name='Graph Poll Interval'),
        ),
        migrations.AddField(
            model_name='task',
            name='message_id',
            field=models.CharField(blank=True, default='', help_text='ID of the Teams channel message that triggered this task', max_length=255, verbose_name='Teams Message ID'),
        ),
    ]
