# Generated by Django 5.2.7 on 2025-10-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_add_teams_message_fields'),
        ('main', '0035_merge_20251024_0922'),
    ]

    operations = [
    ]
