# Generated by Django 5.2.7 on 2025-10-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_merge_20251024_1018'),
        ('main', '0036_merge_20251024_1023'),
    ]

    operations = [
    ]
