# Generated by Django 5.2.7 on 2025-10-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_merge_20251024_1102'),
        ('main', '0037_merge_20251024_1111'),
    ]

    operations = [
    ]
