# Generated by Django 5.2.7 on 2025-10-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_merge_20251024_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='teams_delegated_user_id',
            field=models.CharField(blank=True, default='', help_text='User ID (UPN or email) for delegated authentication', max_length=255, verbose_name='Delegated User ID'),
        ),
        migrations.AddField(
            model_name='settings',
            name='teams_use_delegated_auth',
            field=models.BooleanField(default=True, help_text='Use delegated user authentication (device code flow) for Teams channel posting. Required for posting messages.', verbose_name='Use Delegated Auth for Teams'),
        ),
    ]
