# Generated by Django 5.2.7 on 2025-10-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_add_delegated_auth_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['message_id'], name='task_message_id_idx'),
        ),
    ]
