# Generated by Django 5.2.7 on 2025-10-25 06:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_add_task_message_id_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='changelog',
            field=models.TextField(blank=True, default='', help_text='Markdown ChangeLog für den Milestone'),
        ),
        migrations.CreateModel(
            name='MilestoneFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('file_path', models.CharField(blank=True, default='', help_text='Local file path', max_length=500)),
                ('sharepoint_file_id', models.CharField(blank=True, default='', max_length=255)),
                ('sharepoint_url', models.URLField(blank=True, default='', max_length=1000)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('weaviate_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.milestone')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_milestone_files', to='main.user')),
            ],
            options={
                'verbose_name': 'Milestone File',
                'verbose_name_plural': 'Milestone Files',
                'ordering': ['-created_at'],
            },
        ),
    ]
