# Generated by Django 5.2.7 on 2025-10-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_add_task_comment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Neu'), ('working', 'Working'), ('review', 'Review'), ('ready', 'Ready'), ('test', 'Test'), ('done', 'Erledigt')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature'), ('frage', 'Frage'), ('support', 'Support'), ('idee', 'Idee'), ('sonstige', 'Sonstige')], default='sonstige', help_text='Task type classification', max_length=20),
        ),
    ]
