# Generated by Django 5.2.7 on 2025-10-27 17:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_task_status_alter_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemQuestionAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(help_text='User question about the item')),
                ('answer', models.TextField(blank=True, default='', help_text='AI-generated answer in markdown format')),
                ('sources', models.JSONField(blank=True, default=list, help_text='List of source objects used for answer')),
                ('relevance_score', models.FloatField(default=0.0, help_text='Average relevance score of sources')),
                ('saved_as_knowledge_object', models.BooleanField(default=False, help_text='Whether this Q&A was saved to Weaviate')),
                ('weaviate_uuid', models.CharField(blank=True, default='', help_text='UUID in Weaviate if saved', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asked_questions', to='main.user')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='main.item')),
            ],
            options={
                'verbose_name': 'Item Question Answer',
                'verbose_name_plural': 'Item Question Answers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item', '-created_at'], name='main_itemqu_item_id_101340_idx')],
            },
        ),
    ]
