# Generated by Django 5.2.7 on 2025-10-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_remove_settings_chroma_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='email_from',
            field=models.EmailField(blank=True, default='', help_text='Sender email address', max_length=254),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='email_in_reply_to',
            field=models.CharField(blank=True, default='', help_text='Email In-Reply-To header', max_length=500),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='email_message_id',
            field=models.CharField(blank=True, default='', help_text='Email Message-ID header for threading', max_length=500),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='email_references',
            field=models.TextField(blank=True, default='', help_text='Email References header (space-separated Message-IDs)'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='email_subject',
            field=models.CharField(blank=True, default='', help_text='Email subject line', max_length=500),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='source',
            field=models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('email', 'Email')], default='user', max_length=10),
        ),
    ]
