# Generated by Django 5.2.7 on 2025-10-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_add_email_conversation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='email_cc',
            field=models.TextField(blank=True, default='', help_text='CC email addresses (comma-separated)'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='email_direction',
            field=models.CharField(blank=True, choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='', help_text='Email direction: inbound or outbound', max_length=10),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='email_to',
            field=models.TextField(blank=True, default='', help_text='Recipient email addresses (comma-separated)'),
        ),
    ]
