# Generated by Django 5.2.7 on 2025-10-29 13:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_add_email_fields_to_task_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Template title', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Template description (Markdown)')),
                ('checklist_json', models.JSONField(blank=True, default=list, help_text='Checklist items as JSON array')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_templates', to='main.user')),
                ('default_assignees', models.ManyToManyField(blank=True, help_text='Default assignees for tasks created from this template', related_name='default_task_templates', to='main.user')),
                ('default_item', models.ForeignKey(blank=True, help_text='Default item for tasks created from this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_templates', to='main.item')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags to apply to tasks created from this template', related_name='task_templates', to='main.tag')),
            ],
            options={
                'verbose_name': 'Task Template',
                'verbose_name_plural': 'Task Templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
