# Generated by manual migration for Epic: Verbesserte Task-/GitHub-Integration

from django.db import migrations, models


def migrate_test_to_testing(apps, schema_editor):
    """
    Migrate all tasks with status 'test' to 'testing'
    """
    Task = apps.get_model('main', 'Task')
    Task.objects.filter(status='test').update(status='testing')


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_tasktemplate'),
    ]

    operations = [
        # First, migrate existing data
        migrations.RunPython(migrate_test_to_testing, migrations.RunPython.noop),
        
        # Then, update the field choices
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(
                choices=[
                    ('new', 'Neu'),
                    ('review', 'Review'),
                    ('ready', 'Ready'),
                    ('working', 'Working'),
                    ('testing', 'Testing'),
                    ('done', 'Erledigt')
                ],
                default='new',
                max_length=20
            ),
        ),
    ]
