# Generated by Django 5.2.8 on 2025-11-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_update_task_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='enable_sentry_fetch',
            field=models.BooleanField(default=False, help_text='Enable automatic fetching of errors from Sentry', verbose_name='Enable Sentry Fetch'),
        ),
        migrations.AddField(
            model_name='item',
            name='sentry_dsn',
            field=models.CharField(blank=True, default='', help_text='Sentry DSN for error tracking integration', max_length=500, verbose_name='Sentry DSN'),
        ),
    ]
