# Generated by Django 5.2.8 on 2025-11-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_add_sentry_fields_to_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sentry_project_slug',
            field=models.CharField(blank=True, default='', help_text='Sentry project slug (e.g., ideagraph-v1)', max_length=255, verbose_name='Sentry Project Slug'),
        ),
        migrations.AddField(
            model_name='settings',
            name='sentry_auth_token',
            field=models.CharField(blank=True, default='', help_text='Sentry API authentication token for fetching errors', max_length=255, verbose_name='Sentry Auth Token'),
        ),
    ]
