# Generated by Django 5.2.8 on 2025-11-10 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_add_support_embed_fields'),
        ('main', '0052_item_sentry_project_slug_settings_sentry_auth_token'),
    ]

    operations = [
    ]
