# Generated by Django 5.2.8 on 2025-11-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_item_sentry_project_slug_settings_sentry_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='auto_answer_accepted',
            field=models.BooleanField(default=False, help_text='Whether the user accepted the auto-answer'),
        ),
        migrations.AddField(
            model_name='task',
            name='auto_answer_offered',
            field=models.BooleanField(default=False, help_text='Whether an auto-answer was offered during submission'),
        ),
        migrations.AddField(
            model_name='task',
            name='auto_answer_text',
            field=models.TextField(blank=True, default='', help_text='Text of the auto-answer that was offered'),
        ),
        migrations.AddField(
            model_name='task',
            name='client_fingerprint',
            field=models.CharField(blank=True, default='', help_text='Hash of referrer+UA for rate limiting', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='duplicate_of_task_id',
            field=models.UUIDField(blank=True, help_text='UUID of task this might be a duplicate of', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reporter_email',
            field=models.EmailField(blank=True, default='', help_text='Email of external reporter (for support forms)', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='reporter_referrer',
            field=models.CharField(blank=True, default='', help_text='Referrer URL of external reporter', max_length=500),
        ),
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.CharField(blank=True, default='', help_text='Source of task creation (e.g., "support", "internal")', max_length=50),
        ),
    ]
