# Generated by Django 5.2.8 on 2025-11-10 11:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_merge_20251110_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportEmbedKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('key_prefix', models.CharField(help_text='First 8 chars of key for identification', max_length=16)),
                ('name', models.CharField(help_text='Human-readable name for this key', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this key expires')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When this key was revoked', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this key was used', null=True)),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this key has been used')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_embed_keys', to='main.user')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embed_keys', to='main.item')),
            ],
            options={
                'verbose_name': 'Support Embed Key',
                'verbose_name_plural': 'Support Embed Keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item', 'revoked_at', 'expires_at'], name='main_suppor_item_id_1dc985_idx'), models.Index(fields=['key_hash'], name='main_suppor_key_has_eed601_idx')],
            },
        ),
    ]
