# Generated by Django 5.2.8 on 2025-11-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_merge_20251110_1016'),
        ('main', '0054_add_support_embed_key'),
    ]

    operations = [
    ]
