# Generated by Django 5.2.8 on 2025-11-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_add_support_embed_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sentry_auth_token',
            field=models.CharField(blank=True, default='', help_text='Sentry API authentication token for this item', max_length=255, verbose_name='Sentry Auth Token'),
        ),
    ]
