# Generated by Django 5.2.8 on 2025-11-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='weaviate_grpc_port',
            field=models.IntegerField(default=50051, help_text='Weaviate gRPC port (default: 50051)', verbose_name='WEAVIATE_GRPC'),
        ),
        migrations.AddField(
            model_name='settings',
            name='weaviate_port',
            field=models.IntegerField(default=8081, help_text='Weaviate HTTP port (default: 8081)', verbose_name='WEAVIATE_PORT'),
        ),
        migrations.AddField(
            model_name='settings',
            name='weaviate_timeout',
            field=models.IntegerField(default=30, help_text='Weaviate timeout in seconds (default: 30)', verbose_name='WEAVIATE_TIMEOUT'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='weaviate_url',
            field=models.CharField(blank=True, default='', help_text='Weaviate Cloud URL or local host (e.g., localhost or weaviate for Docker)', max_length=255, verbose_name='WEAVIATE_URL'),
        ),
    ]
