# Generated by Django 5.2.8 on 2025-12-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_add_weaviate_config_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='zammad_api_timeout',
            field=models.IntegerField(default=60, help_text='Timeout in seconds for Zammad API requests (default: 60)', verbose_name='Zammad API Timeout'),
        ),
        migrations.AddField(
            model_name='settings',
            name='zammad_max_retries',
            field=models.IntegerField(default=3, help_text='Maximum number of retries for failed requests (default: 3)', verbose_name='Zammad Max Retries'),
        ),
    ]
